export const validEnv: NodeJS.ProcessEnv = {
  NODE_ENV: "test",
  CONSOLE_DEPLOYMENT_MODE: "development",
  AUTH_ADMIN_URL: "https://auth-admin.example.test",
  OIDC_ISSUER: "https://auth.example.test",
  OIDC_CLIENT_ID: "vkwave-auth-admin",
  OIDC_CLIENT_SECRET: "console-client-secret-32-characters",
  OIDC_REDIRECT_URI: "https://auth-admin.example.test/api/auth/callback",
  OIDC_REQUIRED_ACR: "aal2",
  HYDRA_PUBLIC_URL: "http://hydra-public:4444",
  HYDRA_ADMIN_URL: "http://hydra-admin:4445",
  KRATOS_ADMIN_URL: "http://kratos-admin:4434",
  ADAPTER_INTERNAL_URL: "http://mcp-oauth-adapter:8081",
  ADAPTER_CONSOLE_CLIENT_ID: "auth-admin-console",
  ADAPTER_CONSOLE_CLIENT_SECRET: "adapter-console-secret-32-characters",
  SESSION_SECRET: "console-session-secret-32-characters",
  SESSION_COOKIE_NAME: "vkwave_admin_test",
  ADMIN_ROLE: "auth_admin",
  SECURITY_OPERATOR_ROLE: "security_operator",
  ROLE_RECHECK_SECONDS: "300",
  CONSOLE_ALLOW_INSECURE_DEV: "true",
}
